// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Y3WGGpqfwswBUzUM2lUmNdyAf9UF18k',
    appId: '1:314035904156:web:7cd97fce8efb7ac0a0d759',
    messagingSenderId: '314035904156',
    projectId: 'nrbgymkhanaapp',
    authDomain: 'nrbgymkhanaapp.firebaseapp.com',
    storageBucket: 'nrbgymkhanaapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTuJDlwm0qji5rAAQ_33rrN1ph3B7Zbvc',
    appId: '1:314035904156:android:6743f966ce112b41a0d759',
    messagingSenderId: '314035904156',
    projectId: 'nrbgymkhanaapp',
    storageBucket: 'nrbgymkhanaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCokDK_YnpVJrTliGgl55JQKjxGpobevw8',
    appId: '1:314035904156:ios:2b6f8f45e45171fca0d759',
    messagingSenderId: '314035904156',
    projectId: 'nrbgymkhanaapp',
    storageBucket: 'nrbgymkhanaapp.firebasestorage.app',
    iosBundleId: 'com.nairobigymkhana.nrbgymkhana',
  );

}